package com.cocacola.climateambassador.data;

import java.util.List;
import com.cocacola.climateambassador.data.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BULLET_POINT_FRAME.
 */
public class BulletPointFrame {

    private Long id;
    private String title;
    private String subtitle;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient BulletPointFrameDao myDao;

    private List<BulletPoint> bulletPoints;

    public BulletPointFrame() {
    }

    public BulletPointFrame(Long id) {
        this.id = id;
    }

    public BulletPointFrame(Long id, String title, String subtitle) {
        this.id = id;
        this.title = title;
        this.subtitle = subtitle;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBulletPointFrameDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<BulletPoint> getBulletPoints() {
        if (bulletPoints == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BulletPointDao targetDao = daoSession.getBulletPointDao();
            List<BulletPoint> bulletPointsNew = targetDao._queryBulletPointFrame_BulletPoints(id);
            synchronized (this) {
                if(bulletPoints == null) {
                    bulletPoints = bulletPointsNew;
                }
            }
        }
        return bulletPoints;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetBulletPoints() {
        bulletPoints = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
