package com.cocacola.climateambassador.data;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.cocacola.climateambassador.data.BulletPoint;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BULLET_POINT.
*/
public class BulletPointDao extends AbstractDao<BulletPoint, Long> {

    public static final String TABLENAME = "BULLET_POINT";

    /**
     * Properties of entity BulletPoint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Text = new Property(1, String.class, "text", false, "TEXT");
        public final static Property BulletPointId = new Property(2, long.class, "bulletPointId", false, "BULLET_POINT_ID");
    };

    private Query<BulletPoint> bulletPointFrame_BulletPointsQuery;

    public BulletPointDao(DaoConfig config) {
        super(config);
    }
    
    public BulletPointDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BULLET_POINT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TEXT' TEXT," + // 1: text
                "'BULLET_POINT_ID' INTEGER NOT NULL );"); // 2: bulletPointId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BULLET_POINT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BulletPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(2, text);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BulletPoint readEntity(Cursor cursor, int offset) {
        BulletPoint entity = new BulletPoint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // text
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BulletPoint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setText(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BulletPoint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BulletPoint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "bulletPoints" to-many relationship of BulletPointFrame. */
    public List<BulletPoint> _queryBulletPointFrame_BulletPoints(long bulletPointId) {
        synchronized (this) {
            if (bulletPointFrame_BulletPointsQuery == null) {
                QueryBuilder<BulletPoint> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BulletPointId.eq(null));
                bulletPointFrame_BulletPointsQuery = queryBuilder.build();
            }
        }
        Query<BulletPoint> query = bulletPointFrame_BulletPointsQuery.forCurrentThread();
        query.setParameter(0, bulletPointId);
        return query.list();
    }

}
