package com.cocacola.climateambassador.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BULLET_POINT.
 */
public class BulletPoint {

    private Long id;
    private String text;
    private long bulletPointFrameId;

    public BulletPoint() {
    }

    public BulletPoint(Long id) {
        this.id = id;
    }

    public BulletPoint(Long id, String text, long bulletPointFrameId) {
        this.id = id;
        this.text = text;
        this.bulletPointFrameId = bulletPointFrameId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public long getBulletPointFrameId() {
        return bulletPointFrameId;
    }

    public void setBulletPointFrameId(long bulletPointFrameId) {
        this.bulletPointFrameId = bulletPointFrameId;
    }

}
