package com.cocacola.climateambassador.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.cocacola.climateambassador.data.CaCase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CA_CASE.
*/
public class CaCaseDao extends AbstractDao<CaCase, Long> {

    public static final String TABLENAME = "CA_CASE";

    /**
     * Properties of entity CaCase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property BodyText = new Property(2, String.class, "bodyText", false, "BODY_TEXT");
        public final static Property ModuleId = new Property(3, long.class, "moduleId", false, "MODULE_ID");
        public final static Property BulletPointFrameId = new Property(4, Long.class, "bulletPointFrameId", false, "BULLET_POINT_FRAME_ID");
    };

    private DaoSession daoSession;

    private Query<CaCase> module_CasesQuery;

    public CaCaseDao(DaoConfig config) {
        super(config);
    }
    
    public CaCaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CA_CASE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TITLE' TEXT," + // 1: title
                "'BODY_TEXT' TEXT," + // 2: bodyText
                "'MODULE_ID' INTEGER NOT NULL ," + // 3: moduleId
                "'BULLET_POINT_FRAME_ID' INTEGER);"); // 4: bulletPointFrameId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CA_CASE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CaCase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String bodyText = entity.getBodyText();
        if (bodyText != null) {
            stmt.bindString(3, bodyText);
        }
        stmt.bindLong(4, entity.getModuleId());
 
        Long bulletPointFrameId = entity.getBulletPointFrameId();
        if (bulletPointFrameId != null) {
            stmt.bindLong(5, bulletPointFrameId);
        }
    }

    @Override
    protected void attachEntity(CaCase entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CaCase readEntity(Cursor cursor, int offset) {
        CaCase entity = new CaCase( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bodyText
            cursor.getLong(offset + 3), // moduleId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // bulletPointFrameId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CaCase entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBodyText(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setModuleId(cursor.getLong(offset + 3));
        entity.setBulletPointFrameId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CaCase entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CaCase entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "cases" to-many relationship of Module. */
    public List<CaCase> _queryModule_Cases(long moduleId) {
        synchronized (this) {
            if (module_CasesQuery == null) {
                QueryBuilder<CaCase> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ModuleId.eq(null));
                module_CasesQuery = queryBuilder.build();
            }
        }
        Query<CaCase> query = module_CasesQuery.forCurrentThread();
        query.setParameter(0, moduleId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBulletPointFrameDao().getAllColumns());
            builder.append(" FROM CA_CASE T");
            builder.append(" LEFT JOIN BULLET_POINT_FRAME T0 ON T.'BULLET_POINT_FRAME_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CaCase loadCurrentDeep(Cursor cursor, boolean lock) {
        CaCase entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BulletPointFrame bulletPointFrame = loadCurrentOther(daoSession.getBulletPointFrameDao(), cursor, offset);
        entity.setBulletPointFrame(bulletPointFrame);

        return entity;    
    }

    public CaCase loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CaCase> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CaCase> list = new ArrayList<CaCase>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CaCase> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CaCase> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
