package com.cocacola.climateambassador.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cocacola.climateambassador.data.Section;
import com.cocacola.climateambassador.data.Module;
import com.cocacola.climateambassador.data.Document;
import com.cocacola.climateambassador.data.BulletPointFrame;
import com.cocacola.climateambassador.data.BulletPoint;

import com.cocacola.climateambassador.data.SectionDao;
import com.cocacola.climateambassador.data.ModuleDao;
import com.cocacola.climateambassador.data.DocumentDao;
import com.cocacola.climateambassador.data.BulletPointFrameDao;
import com.cocacola.climateambassador.data.BulletPointDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sectionDaoConfig;
    private final DaoConfig moduleDaoConfig;
    private final DaoConfig documentDaoConfig;
    private final DaoConfig bulletPointFrameDaoConfig;
    private final DaoConfig bulletPointDaoConfig;

    private final SectionDao sectionDao;
    private final ModuleDao moduleDao;
    private final DocumentDao documentDao;
    private final BulletPointFrameDao bulletPointFrameDao;
    private final BulletPointDao bulletPointDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sectionDaoConfig = daoConfigMap.get(SectionDao.class).clone();
        sectionDaoConfig.initIdentityScope(type);

        moduleDaoConfig = daoConfigMap.get(ModuleDao.class).clone();
        moduleDaoConfig.initIdentityScope(type);

        documentDaoConfig = daoConfigMap.get(DocumentDao.class).clone();
        documentDaoConfig.initIdentityScope(type);

        bulletPointFrameDaoConfig = daoConfigMap.get(BulletPointFrameDao.class).clone();
        bulletPointFrameDaoConfig.initIdentityScope(type);

        bulletPointDaoConfig = daoConfigMap.get(BulletPointDao.class).clone();
        bulletPointDaoConfig.initIdentityScope(type);

        sectionDao = new SectionDao(sectionDaoConfig, this);
        moduleDao = new ModuleDao(moduleDaoConfig, this);
        documentDao = new DocumentDao(documentDaoConfig, this);
        bulletPointFrameDao = new BulletPointFrameDao(bulletPointFrameDaoConfig, this);
        bulletPointDao = new BulletPointDao(bulletPointDaoConfig, this);

        registerDao(Section.class, sectionDao);
        registerDao(Module.class, moduleDao);
        registerDao(Document.class, documentDao);
        registerDao(BulletPointFrame.class, bulletPointFrameDao);
        registerDao(BulletPoint.class, bulletPointDao);
    }
    
    public void clear() {
        sectionDaoConfig.getIdentityScope().clear();
        moduleDaoConfig.getIdentityScope().clear();
        documentDaoConfig.getIdentityScope().clear();
        bulletPointFrameDaoConfig.getIdentityScope().clear();
        bulletPointDaoConfig.getIdentityScope().clear();
    }

    public SectionDao getSectionDao() {
        return sectionDao;
    }

    public ModuleDao getModuleDao() {
        return moduleDao;
    }

    public DocumentDao getDocumentDao() {
        return documentDao;
    }

    public BulletPointFrameDao getBulletPointFrameDao() {
        return bulletPointFrameDao;
    }

    public BulletPointDao getBulletPointDao() {
        return bulletPointDao;
    }

}
