package com.cocacola.climateambassador.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOCUMENT.
 */
public class Document {

    private Long id;
    private String fileName;
    private String label;
    private long moduleId;

    public Document() {
    }

    public Document(Long id) {
        this.id = id;
    }

    public Document(Long id, String fileName, String label, long moduleId) {
        this.id = id;
        this.fileName = fileName;
        this.label = label;
        this.moduleId = moduleId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public long getModuleId() {
        return moduleId;
    }

    public void setModuleId(long moduleId) {
        this.moduleId = moduleId;
    }

}
