package com.cocacola.climateambassador.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.cocacola.climateambassador.data.Module;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MODULE.
*/
public class ModuleDao extends AbstractDao<Module, Long> {

    public static final String TABLENAME = "MODULE";

    /**
     * Properties of entity Module.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SectionId = new Property(1, long.class, "sectionId", false, "SECTION_ID");
        public final static Property DocumentId = new Property(2, long.class, "documentId", false, "DOCUMENT_ID");
        public final static Property BulletPointId = new Property(3, Long.class, "bulletPointId", false, "BULLET_POINT_ID");
    };

    private DaoSession daoSession;

    private Query<Module> section_ModulesQuery;

    public ModuleDao(DaoConfig config) {
        super(config);
    }
    
    public ModuleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MODULE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SECTION_ID' INTEGER NOT NULL ," + // 1: sectionId
                "'DOCUMENT_ID' INTEGER NOT NULL ," + // 2: documentId
                "'BULLET_POINT_ID' INTEGER);"); // 3: bulletPointId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MODULE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Module entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSectionId());
        stmt.bindLong(3, entity.getDocumentId());
 
        Long bulletPointId = entity.getBulletPointId();
        if (bulletPointId != null) {
            stmt.bindLong(4, bulletPointId);
        }
    }

    @Override
    protected void attachEntity(Module entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Module readEntity(Cursor cursor, int offset) {
        Module entity = new Module( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // sectionId
            cursor.getLong(offset + 2), // documentId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // bulletPointId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Module entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSectionId(cursor.getLong(offset + 1));
        entity.setDocumentId(cursor.getLong(offset + 2));
        entity.setBulletPointId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Module entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Module entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "modules" to-many relationship of Section. */
    public List<Module> _querySection_Modules(long sectionId) {
        synchronized (this) {
            if (section_ModulesQuery == null) {
                QueryBuilder<Module> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SectionId.eq(null));
                section_ModulesQuery = queryBuilder.build();
            }
        }
        Query<Module> query = section_ModulesQuery.forCurrentThread();
        query.setParameter(0, sectionId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBulletPointFrameDao().getAllColumns());
            builder.append(" FROM MODULE T");
            builder.append(" LEFT JOIN BULLET_POINT_FRAME T0 ON T.'BULLET_POINT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Module loadCurrentDeep(Cursor cursor, boolean lock) {
        Module entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BulletPointFrame bulletPointFrame = loadCurrentOther(daoSession.getBulletPointFrameDao(), cursor, offset);
        entity.setBulletPointFrame(bulletPointFrame);

        return entity;    
    }

    public Module loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Module> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Module> list = new ArrayList<Module>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Module> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Module> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
