package com.cocacola.climateambassador.data;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.cocacola.climateambassador.data.TextFrame;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TEXT_FRAME.
*/
public class TextFrameDao extends AbstractDao<TextFrame, Long> {

    public static final String TABLENAME = "TEXT_FRAME";

    /**
     * Properties of entity TextFrame.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property BodyText = new Property(2, String.class, "bodyText", false, "BODY_TEXT");
        public final static Property CaseId = new Property(3, Long.class, "caseId", false, "CASE_ID");
    };

    private DaoSession daoSession;

    private Query<TextFrame> caCase_TextFramesQuery;

    public TextFrameDao(DaoConfig config) {
        super(config);
    }
    
    public TextFrameDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TEXT_FRAME' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TITLE' TEXT," + // 1: title
                "'BODY_TEXT' TEXT," + // 2: bodyText
                "'CASE_ID' INTEGER);"); // 3: caseId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TEXT_FRAME'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TextFrame entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String bodyText = entity.getBodyText();
        if (bodyText != null) {
            stmt.bindString(3, bodyText);
        }
 
        Long caseId = entity.getCaseId();
        if (caseId != null) {
            stmt.bindLong(4, caseId);
        }
    }

    @Override
    protected void attachEntity(TextFrame entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TextFrame readEntity(Cursor cursor, int offset) {
        TextFrame entity = new TextFrame( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bodyText
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // caseId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TextFrame entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBodyText(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCaseId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TextFrame entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TextFrame entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "textFrames" to-many relationship of CaCase. */
    public List<TextFrame> _queryCaCase_TextFrames(Long caseId) {
        synchronized (this) {
            if (caCase_TextFramesQuery == null) {
                QueryBuilder<TextFrame> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CaseId.eq(null));
                caCase_TextFramesQuery = queryBuilder.build();
            }
        }
        Query<TextFrame> query = caCase_TextFramesQuery.forCurrentThread();
        query.setParameter(0, caseId);
        return query.list();
    }

}
